version: '3.8'
services:
    postgres:
        image: postgres:latest
        container_name: batch-db
        environment:
            POSTGRES_DB: batchdb
            POSTGRES_USER: batchuser
            POSTGRES_PASSWORD: batchpass
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:    