// <auto-generated />
using System;
using BatchProcessing.Infraestructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BatchProcessing.Migrations
{
    [DbContext(typeof(BatchDbContext))]
    [Migration("20250611222313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BatchProcessing.Models.TransactionProcessed", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TransactionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<decimal>("AmountLocalCurrency")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AmountLocalCurrency");

                    b.Property<string>("AuthorizationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("AuthorizationCode");

                    b.Property<DateTime>("AuthorizationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("AuthorizationDate");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CardHolderName");

                    b.Property<string>("CardNumberMasked")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("CardNumberMasked");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CardType");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("Currency");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Date");

                    b.Property<string>("EntryMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("EntryMode");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("ExchangeRate");

                    b.Property<bool>("IsFraudSuspected")
                        .HasColumnType("boolean")
                        .HasColumnName("IsFraudSuspected");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("boolean")
                        .HasColumnName("IsInternational");

                    b.Property<bool>("IsOfflineTransaction")
                        .HasColumnType("boolean")
                        .HasColumnName("IsOfflineTransaction");

                    b.Property<string>("LocalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("LocalCurrency");

                    b.Property<string>("MerchantCategoryCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("MerchantCategoryCode");

                    b.Property<string>("MerchantCountry")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("MerchantCountry");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("MerchantId");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MerchantName");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<string>("POSCountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("POSCountryCode");

                    b.Property<string>("POSLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("POSLocation");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("PostingDate");

                    b.Property<DateTime>("ProcessedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ProcessedDate");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ReferenceNumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TerminalId");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TransactionType");

                    b.HasKey("TransactionId");

                    b.ToTable("TRANSACTIONS_PROCESSED", (string)null);
                });

            modelBuilder.Entity("BatchProcessing.Models.TransactionRaw", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TransactionId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<decimal>("AmountLocalCurrency")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AmountLocalCurrency");

                    b.Property<string>("AuthorizationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("AuthorizationCode");

                    b.Property<DateTime>("AuthorizationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("AuthorizationDate");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CardHolderName");

                    b.Property<string>("CardNumberMasked")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("CardNumberMasked");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CardType");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("Currency");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CustomerId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Date");

                    b.Property<string>("EntryMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("EntryMode");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("ExchangeRate");

                    b.Property<bool>("IsFraudSuspected")
                        .HasColumnType("boolean")
                        .HasColumnName("IsFraudSuspected");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("boolean")
                        .HasColumnName("IsInternational");

                    b.Property<bool>("IsOfflineTransaction")
                        .HasColumnType("boolean")
                        .HasColumnName("IsOfflineTransaction");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("IsProcessed");

                    b.Property<string>("LocalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("LocalCurrency");

                    b.Property<string>("MerchantCategoryCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("MerchantCategoryCode");

                    b.Property<string>("MerchantCountry")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("MerchantCountry");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("MerchantId");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MerchantName");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<string>("POSCountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("POSCountryCode");

                    b.Property<string>("POSLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("POSLocation");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("PostingDate");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ReferenceNumber");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Status");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TerminalId");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TransactionType");

                    b.HasKey("TransactionId");

                    b.ToTable("TRANSACTIONS_IN", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
